//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMTHI
    {
        public string MaSV { get; set; }
        public string MaHP { get; set; }
        public Nullable<decimal> DiemGiuaKy { get; set; }
        public Nullable<decimal> DiemCuoiKy { get; set; }
        public Nullable<bool> DaDongHP { get; set; }
    
        public virtual HOCPHAN HOCPHAN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
