//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDRENLUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDRENLUYEN()
        {
            this.DSSV_HDRENLYEN = new HashSet<DSSV_HDRENLYEN>();
        }
    
        public string MaHDRL { get; set; }
        public string TenHDRL { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<System.DateTime> NgayTC { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> HocKy { get; set; }
        public Nullable<int> SoDiemRL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSSV_HDRENLYEN> DSSV_HDRENLYEN { get; set; }
    }
}
