//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCPHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCPHAN()
        {
            this.DIEMTHIs = new HashSet<DIEMTHI>();
        }
    
        public string MaHP { get; set; }
        public string MaMH { get; set; }
        public Nullable<int> HocKy { get; set; }
        public string NamHoc { get; set; }
        public string MaGV { get; set; }
        public Nullable<int> SoTC { get; set; }
        public Nullable<int> HocPhi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMTHI> DIEMTHIs { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
