//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBQuanLySinhVienEntities : DbContext
    {
        public DBQuanLySinhVienEntities()
            : base("name=DBQuanLySinhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUYENNGANH> CHUYENNGANHs { get; set; }
        public virtual DbSet<DIEMTHI> DIEMTHIs { get; set; }
        public virtual DbSet<DSSV_HDRENLYEN> DSSV_HDRENLYEN { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIENs { get; set; }
        public virtual DbSet<HDCTXH> HDCTXHs { get; set; }
        public virtual DbSet<HDRENLUYEN> HDRENLUYENs { get; set; }
        public virtual DbSet<HOCPHAN> HOCPHANs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<MONHOC> MONHOCs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<VIPHAM> VIPHAMs { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<spGetChuyenNganh_Result> spGetChuyenNganh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetChuyenNganh_Result>("spGetChuyenNganh");
        }
    
        public virtual ObjectResult<spGetCNTheoKhoa_Result> spGetCNTheoKhoa(string maKhoa)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCNTheoKhoa_Result>("spGetCNTheoKhoa", maKhoaParameter);
        }
    
        public virtual ObjectResult<spGetCNTheoMaCN_Result> spGetCNTheoMaCN(string maCN)
        {
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCNTheoMaCN_Result>("spGetCNTheoMaCN", maCNParameter);
        }
    
        public virtual ObjectResult<spGetDiemTB_SoTC_Result> spGetDiemTB_SoTC(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDiemTB_SoTC_Result>("spGetDiemTB_SoTC", maSVParameter);
        }
    
        public virtual ObjectResult<spGetDiemTBTL_SoTCTL_Result> spGetDiemTBTL_SoTCTL(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDiemTBTL_SoTCTL_Result>("spGetDiemTBTL_SoTCTL", maSVParameter);
        }
    
        public virtual ObjectResult<spGetDiemTheoMSSV_Result> spGetDiemTheoMSSV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDiemTheoMSSV_Result>("spGetDiemTheoMSSV", maSVParameter);
        }
    
        public virtual ObjectResult<spGetDiemTheoMSSV_MaHP_Result> spGetDiemTheoMSSV_MaHP(string maSV, string maHP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maHPParameter = maHP != null ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDiemTheoMSSV_MaHP_Result>("spGetDiemTheoMSSV_MaHP", maSVParameter, maHPParameter);
        }
    
        public virtual ObjectResult<spGetDSSVCanhBaoHV_Result> spGetDSSVCanhBaoHV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDSSVCanhBaoHV_Result>("spGetDSSVCanhBaoHV");
        }
    
        public virtual ObjectResult<spGetGVTheoMaGV_Result> spGetGVTheoMaGV(string maGV)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetGVTheoMaGV_Result>("spGetGVTheoMaGV", maGVParameter);
        }
    
        public virtual ObjectResult<spGetGVTheoMaKhoa_Result> spGetGVTheoMaKhoa(string maKhoa)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetGVTheoMaKhoa_Result>("spGetGVTheoMaKhoa", maKhoaParameter);
        }
    
        public virtual ObjectResult<spGetHBGioi_NamHoc_HocKy_Result> spGetHBGioi_NamHoc_HocKy(string namHoc, Nullable<int> hocKy)
        {
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHBGioi_NamHoc_HocKy_Result>("spGetHBGioi_NamHoc_HocKy", namHocParameter, hocKyParameter);
        }
    
        public virtual ObjectResult<spGetHBKha_NamHoc_HocKy_Result> spGetHBKha_NamHoc_HocKy(string namHoc, Nullable<int> hocKy)
        {
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHBKha_NamHoc_HocKy_Result>("spGetHBKha_NamHoc_HocKy", namHocParameter, hocKyParameter);
        }
    
        public virtual ObjectResult<spGetHBNhatLop_NamHoc_HocKy_Result> spGetHBNhatLop_NamHoc_HocKy(string namHoc, Nullable<int> hocKy)
        {
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHBNhatLop_NamHoc_HocKy_Result>("spGetHBNhatLop_NamHoc_HocKy", namHocParameter, hocKyParameter);
        }
    
        public virtual ObjectResult<spgetHDByMaHD_Result> spgetHDByMaHD(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetHDByMaHD_Result>("spgetHDByMaHD", maHDParameter);
        }
    
        public virtual ObjectResult<spGetHDCTXHByMaSV_Result> spGetHDCTXHByMaSV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHDCTXHByMaSV_Result>("spGetHDCTXHByMaSV", maSVParameter);
        }
    
        public virtual ObjectResult<spGetHDRLByMaHD_Result> spGetHDRLByMaHD(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHDRLByMaHD_Result>("spGetHDRLByMaHD", maHDParameter);
        }
    
        public virtual ObjectResult<spGetHDRLByMaSV_NamHoc_HocKy_Result> spGetHDRLByMaSV_NamHoc_HocKy(string maSV, string namHoc, Nullable<int> hocKy)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHDRLByMaSV_NamHoc_HocKy_Result>("spGetHDRLByMaSV_NamHoc_HocKy", maSVParameter, namHocParameter, hocKyParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetHocKy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetHocKy");
        }
    
        public virtual ObjectResult<spGetHPByMaSV_Result> spGetHPByMaSV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHPByMaSV_Result>("spGetHPByMaSV", maSVParameter);
        }
    
        public virtual ObjectResult<spGetHPTheoMaHP_Result> spGetHPTheoMaHP(string maHP)
        {
            var maHPParameter = maHP != null ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHPTheoMaHP_Result>("spGetHPTheoMaHP", maHPParameter);
        }
    
        public virtual ObjectResult<spGetHPTheoMH_Result> spGetHPTheoMH(string maMH)
        {
            var maMHParameter = maMH != null ?
                new ObjectParameter("maMH", maMH) :
                new ObjectParameter("maMH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetHPTheoMH_Result>("spGetHPTheoMH", maMHParameter);
        }
    
        public virtual ObjectResult<spGetKhoa_Result> spGetKhoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetKhoa_Result>("spGetKhoa");
        }
    
        public virtual ObjectResult<spGetKTheoMaKhoa_Result> spGetKTheoMaKhoa(string maKhoa)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetKTheoMaKhoa_Result>("spGetKTheoMaKhoa", maKhoaParameter);
        }
    
        public virtual ObjectResult<spGetLop_Result> spGetLop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLop_Result>("spGetLop");
        }
    
        public virtual ObjectResult<spGetLopTheoChuyenNganh_Result> spGetLopTheoChuyenNganh(string maCN)
        {
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLopTheoChuyenNganh_Result>("spGetLopTheoChuyenNganh", maCNParameter);
        }
    
        public virtual ObjectResult<spGetLopTheoMaLop_Result> spGetLopTheoMaLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLopTheoMaLop_Result>("spGetLopTheoMaLop", maLopParameter);
        }
    
        public virtual ObjectResult<string> spGetMaGV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetMaGV");
        }
    
        public virtual ObjectResult<string> spGetMaHDCTXH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetMaHDCTXH");
        }
    
        public virtual ObjectResult<string> spGetMaHDRL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetMaHDRL");
        }
    
        public virtual ObjectResult<spGetMHTheoMaMH_Result> spGetMHTheoMaMH(string maMH)
        {
            var maMHParameter = maMH != null ?
                new ObjectParameter("maMH", maMH) :
                new ObjectParameter("maMH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetMHTheoMaMH_Result>("spGetMHTheoMaMH", maMHParameter);
        }
    
        public virtual ObjectResult<spGetMHTrongHP_Result> spGetMHTrongHP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetMHTrongHP_Result>("spGetMHTrongHP");
        }
    
        public virtual ObjectResult<spGetMHTrongHPTheoGV_Result> spGetMHTrongHPTheoGV(string maGV)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetMHTrongHPTheoGV_Result>("spGetMHTrongHPTheoGV", maGVParameter);
        }
    
        public virtual ObjectResult<spGetMonHoc_Result> spGetMonHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetMonHoc_Result>("spGetMonHoc");
        }
    
        public virtual ObjectResult<string> spGetMSSV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetMSSV");
        }
    
        public virtual ObjectResult<string> spGetNamHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetNamHoc");
        }
    
        public virtual ObjectResult<Nullable<int>> spGetSiSoLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetSiSoLop", maLopParameter);
        }
    
        public virtual ObjectResult<spGetSVByMaCTXH_Result> spGetSVByMaCTXH(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVByMaCTXH_Result>("spGetSVByMaCTXH", maHDParameter);
        }
    
        public virtual ObjectResult<spGetSVByMaRL_Result> spGetSVByMaRL(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVByMaRL_Result>("spGetSVByMaRL", maHDParameter);
        }
    
        public virtual ObjectResult<spGetSVByMaSV_MaHDCTXH_Result> spGetSVByMaSV_MaHDCTXH(string maHD, string maSV)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(string));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVByMaSV_MaHDCTXH_Result>("spGetSVByMaSV_MaHDCTXH", maHDParameter, maSVParameter);
        }
    
        public virtual ObjectResult<spGetSVByMaSV_MaHDRL_Result> spGetSVByMaSV_MaHDRL(string maSV, string maHDRL)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maHDRLParameter = maHDRL != null ?
                new ObjectParameter("MaHDRL", maHDRL) :
                new ObjectParameter("MaHDRL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVByMaSV_MaHDRL_Result>("spGetSVByMaSV_MaHDRL", maSVParameter, maHDRLParameter);
        }
    
        public virtual ObjectResult<spGetSVNoHocPhi_Result> spGetSVNoHocPhi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVNoHocPhi_Result>("spGetSVNoHocPhi");
        }
    
        public virtual ObjectResult<spGetSVTheoMaHP_Result> spGetSVTheoMaHP(string maHP)
        {
            var maHPParameter = maHP != null ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVTheoMaHP_Result>("spGetSVTheoMaHP", maHPParameter);
        }
    
        public virtual ObjectResult<spGetSVTheoMaLop_Result> spGetSVTheoMaLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVTheoMaLop_Result>("spGetSVTheoMaLop", maLopParameter);
        }
    
        public virtual ObjectResult<spGetSVTheoMaSV_Result> spGetSVTheoMaSV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVTheoMaSV_Result>("spGetSVTheoMaSV", maSVParameter);
        }
    
        public virtual ObjectResult<spGetSVThieuDiemCTXH_Result> spGetSVThieuDiemCTXH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSVThieuDiemCTXH_Result>("spGetSVThieuDiemCTXH");
        }
    
        public virtual ObjectResult<spGetTaiKhoan_Result> spGetTaiKhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTaiKhoan_Result>("spGetTaiKhoan");
        }
    
        public virtual ObjectResult<spGetTKTheoLoaiUser_Result> spGetTKTheoLoaiUser(string loaiUser)
        {
            var loaiUserParameter = loaiUser != null ?
                new ObjectParameter("loaiUser", loaiUser) :
                new ObjectParameter("loaiUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTKTheoLoaiUser_Result>("spGetTKTheoLoaiUser", loaiUserParameter);
        }
    
        public virtual ObjectResult<spGetTKTheoMa_Result> spGetTKTheoMa(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTKTheoMa_Result>("spGetTKTheoMa", maParameter);
        }
    
        public virtual ObjectResult<spGetTKTheoTK_Result> spGetTKTheoTK(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTKTheoTK_Result>("spGetTKTheoTK", userParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetTongDiemCongRLByMaSV_NamHoc_HocKy(string maSV, string namHoc, Nullable<int> hocKy)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetTongDiemCongRLByMaSV_NamHoc_HocKy", maSVParameter, namHocParameter, hocKyParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetTongDiemHDCTXHByMaSV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetTongDiemHDCTXHByMaSV", maSVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetTongDiemTruRLByMaSV_NamHoc_HocKy(string maSV, string namHoc, Nullable<int> hocKy)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetTongDiemTruRLByMaSV_NamHoc_HocKy", maSVParameter, namHocParameter, hocKyParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetTongNoHPByMaSV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetTongNoHPByMaSV", maSVParameter);
        }
    
        public virtual ObjectResult<spGetUserByIDPass_Result> spGetUserByIDPass(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUserByIDPass_Result>("spGetUserByIDPass", userParameter, passParameter);
        }
    
        public virtual ObjectResult<spGetViPham_Result> spGetViPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetViPham_Result>("spGetViPham");
        }
    
        public virtual ObjectResult<spGetVPByAllKey_Result> spGetVPByAllKey(string maSV, string noiDung, string hinhthucKL, Nullable<System.DateTime> ngayVP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("noiDung", noiDung) :
                new ObjectParameter("noiDung", typeof(string));
    
            var hinhthucKLParameter = hinhthucKL != null ?
                new ObjectParameter("hinhthucKL", hinhthucKL) :
                new ObjectParameter("hinhthucKL", typeof(string));
    
            var ngayVPParameter = ngayVP.HasValue ?
                new ObjectParameter("ngayVP", ngayVP) :
                new ObjectParameter("ngayVP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetVPByAllKey_Result>("spGetVPByAllKey", maSVParameter, noiDungParameter, hinhthucKLParameter, ngayVPParameter);
        }
    
        public virtual ObjectResult<spGetVPByMaSV_Result> spGetVPByMaSV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetVPByMaSV_Result>("spGetVPByMaSV", maSVParameter);
        }
    
        public virtual int spSuaChuyenNganh(string maCN, string tenChuyenNganh, string maKhoa)
        {
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            var tenChuyenNganhParameter = tenChuyenNganh != null ?
                new ObjectParameter("tenChuyenNganh", tenChuyenNganh) :
                new ObjectParameter("tenChuyenNganh", typeof(string));
    
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaChuyenNganh", maCNParameter, tenChuyenNganhParameter, maKhoaParameter);
        }
    
        public virtual int spSuaCTXH(string maHDCTXH, string tenHDCTXH, string diaDiem, Nullable<System.DateTime> ngayTC, Nullable<int> soDiemCTXH)
        {
            var maHDCTXHParameter = maHDCTXH != null ?
                new ObjectParameter("MaHDCTXH", maHDCTXH) :
                new ObjectParameter("MaHDCTXH", typeof(string));
    
            var tenHDCTXHParameter = tenHDCTXH != null ?
                new ObjectParameter("TenHDCTXH", tenHDCTXH) :
                new ObjectParameter("TenHDCTXH", typeof(string));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            var ngayTCParameter = ngayTC.HasValue ?
                new ObjectParameter("NgayTC", ngayTC) :
                new ObjectParameter("NgayTC", typeof(System.DateTime));
    
            var soDiemCTXHParameter = soDiemCTXH.HasValue ?
                new ObjectParameter("SoDiemCTXH", soDiemCTXH) :
                new ObjectParameter("SoDiemCTXH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaCTXH", maHDCTXHParameter, tenHDCTXHParameter, diaDiemParameter, ngayTCParameter, soDiemCTXHParameter);
        }
    
        public virtual int spSuaDiemThi(string maSV, string maHP, Nullable<decimal> diemGK, Nullable<decimal> diemCK)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maHPParameter = maHP != null ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(string));
    
            var diemGKParameter = diemGK.HasValue ?
                new ObjectParameter("diemGK", diemGK) :
                new ObjectParameter("diemGK", typeof(decimal));
    
            var diemCKParameter = diemCK.HasValue ?
                new ObjectParameter("diemCK", diemCK) :
                new ObjectParameter("diemCK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaDiemThi", maSVParameter, maHPParameter, diemGKParameter, diemCKParameter);
        }
    
        public virtual int spSuaGiangVien(string magv, string tengv, string thuocmakhoa, string hocvi, string diachi, string sdt)
        {
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            var tengvParameter = tengv != null ?
                new ObjectParameter("tengv", tengv) :
                new ObjectParameter("tengv", typeof(string));
    
            var thuocmakhoaParameter = thuocmakhoa != null ?
                new ObjectParameter("thuocmakhoa", thuocmakhoa) :
                new ObjectParameter("thuocmakhoa", typeof(string));
    
            var hocviParameter = hocvi != null ?
                new ObjectParameter("hocvi", hocvi) :
                new ObjectParameter("hocvi", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaGiangVien", magvParameter, tengvParameter, thuocmakhoaParameter, hocviParameter, diachiParameter, sdtParameter);
        }
    
        public virtual int spSuaHocPhan(string mahp, string mamh, Nullable<int> hocky, string namhoc, string magv, Nullable<int> sotc, Nullable<int> hocphi)
        {
            var mahpParameter = mahp != null ?
                new ObjectParameter("mahp", mahp) :
                new ObjectParameter("mahp", typeof(string));
    
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            var hockyParameter = hocky.HasValue ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(int));
    
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            var sotcParameter = sotc.HasValue ?
                new ObjectParameter("sotc", sotc) :
                new ObjectParameter("sotc", typeof(int));
    
            var hocphiParameter = hocphi.HasValue ?
                new ObjectParameter("hocphi", hocphi) :
                new ObjectParameter("hocphi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaHocPhan", mahpParameter, mamhParameter, hockyParameter, namhocParameter, magvParameter, sotcParameter, hocphiParameter);
        }
    
        public virtual int spSuaKhoa(string maKhoa, string tenKhoa, string truongKhoa, string sDT)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("tenKhoa", tenKhoa) :
                new ObjectParameter("tenKhoa", typeof(string));
    
            var truongKhoaParameter = truongKhoa != null ?
                new ObjectParameter("truongKhoa", truongKhoa) :
                new ObjectParameter("truongKhoa", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaKhoa", maKhoaParameter, tenKhoaParameter, truongKhoaParameter, sDTParameter);
        }
    
        public virtual int spSuaLop(string maLop, string chuyenNganh)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            var chuyenNganhParameter = chuyenNganh != null ?
                new ObjectParameter("chuyenNganh", chuyenNganh) :
                new ObjectParameter("chuyenNganh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaLop", maLopParameter, chuyenNganhParameter);
        }
    
        public virtual int spSuaMonHoc(string maMH, string tenMH)
        {
            var maMHParameter = maMH != null ?
                new ObjectParameter("maMH", maMH) :
                new ObjectParameter("maMH", typeof(string));
    
            var tenMHParameter = tenMH != null ?
                new ObjectParameter("tenMH", tenMH) :
                new ObjectParameter("tenMH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaMonHoc", maMHParameter, tenMHParameter);
        }
    
        public virtual int spSuaRL(string maHDRL, string tenHDRL, string diaDiem, Nullable<System.DateTime> ngayTC, string namHoc, Nullable<int> hocKy, Nullable<int> soDiemRL)
        {
            var maHDRLParameter = maHDRL != null ?
                new ObjectParameter("MaHDRL", maHDRL) :
                new ObjectParameter("MaHDRL", typeof(string));
    
            var tenHDRLParameter = tenHDRL != null ?
                new ObjectParameter("TenHDRL", tenHDRL) :
                new ObjectParameter("TenHDRL", typeof(string));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            var ngayTCParameter = ngayTC.HasValue ?
                new ObjectParameter("NgayTC", ngayTC) :
                new ObjectParameter("NgayTC", typeof(System.DateTime));
    
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            var soDiemRLParameter = soDiemRL.HasValue ?
                new ObjectParameter("SoDiemRL", soDiemRL) :
                new ObjectParameter("SoDiemRL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaRL", maHDRLParameter, tenHDRLParameter, diaDiemParameter, ngayTCParameter, namHocParameter, hocKyParameter, soDiemRLParameter);
        }
    
        public virtual int spSuaSinhVien(string maSV, string hoTen, string diaChi, Nullable<System.DateTime> ngaySinh, string gioiTinh, string danToc, string queQuan, string maLop)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("danToc", danToc) :
                new ObjectParameter("danToc", typeof(string));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("queQuan", queQuan) :
                new ObjectParameter("queQuan", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaSinhVien", maSVParameter, hoTenParameter, diaChiParameter, ngaySinhParameter, gioiTinhParameter, danTocParameter, queQuanParameter, maLopParameter);
        }
    
        public virtual int spSuaTaiKhoan(string maTk, string matKhau, string loaiUser, string magv)
        {
            var maTkParameter = maTk != null ?
                new ObjectParameter("maTk", maTk) :
                new ObjectParameter("maTk", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            var loaiUserParameter = loaiUser != null ?
                new ObjectParameter("loaiUser", loaiUser) :
                new ObjectParameter("loaiUser", typeof(string));
    
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaTaiKhoan", maTkParameter, matKhauParameter, loaiUserParameter, magvParameter);
        }
    
        public virtual int spSuaTinhTrangHP(string maSV, string maHP, Nullable<bool> daDongHP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maHPParameter = maHP != null ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(string));
    
            var daDongHPParameter = daDongHP.HasValue ?
                new ObjectParameter("daDongHP", daDongHP) :
                new ObjectParameter("daDongHP", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaTinhTrangHP", maSVParameter, maHPParameter, daDongHPParameter);
        }
    
        public virtual int spThemChuyenNganh(string maCN, string tenChuyenNganh, string maKhoa)
        {
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            var tenChuyenNganhParameter = tenChuyenNganh != null ?
                new ObjectParameter("tenChuyenNganh", tenChuyenNganh) :
                new ObjectParameter("tenChuyenNganh", typeof(string));
    
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemChuyenNganh", maCNParameter, tenChuyenNganhParameter, maKhoaParameter);
        }
    
        public virtual int spThemCTXH(string maHDCTXH, string tenHDCTXH, string diaDiem, Nullable<System.DateTime> ngayTC, Nullable<int> soDiemCTXH)
        {
            var maHDCTXHParameter = maHDCTXH != null ?
                new ObjectParameter("MaHDCTXH", maHDCTXH) :
                new ObjectParameter("MaHDCTXH", typeof(string));
    
            var tenHDCTXHParameter = tenHDCTXH != null ?
                new ObjectParameter("TenHDCTXH", tenHDCTXH) :
                new ObjectParameter("TenHDCTXH", typeof(string));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            var ngayTCParameter = ngayTC.HasValue ?
                new ObjectParameter("NgayTC", ngayTC) :
                new ObjectParameter("NgayTC", typeof(System.DateTime));
    
            var soDiemCTXHParameter = soDiemCTXH.HasValue ?
                new ObjectParameter("SoDiemCTXH", soDiemCTXH) :
                new ObjectParameter("SoDiemCTXH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemCTXH", maHDCTXHParameter, tenHDCTXHParameter, diaDiemParameter, ngayTCParameter, soDiemCTXHParameter);
        }
    
        public virtual int spThemDiemThi(string maHP, string maSV)
        {
            var maHPParameter = maHP != null ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(string));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemDiemThi", maHPParameter, maSVParameter);
        }
    
        public virtual int spThemDSSV_HDCTXH(string maHD, string maSV)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(string));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemDSSV_HDCTXH", maHDParameter, maSVParameter);
        }
    
        public virtual int spThemDSSV_HDRL(string maSV, string maHDRL, Nullable<bool> coMat)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maHDRLParameter = maHDRL != null ?
                new ObjectParameter("MaHDRL", maHDRL) :
                new ObjectParameter("MaHDRL", typeof(string));
    
            var coMatParameter = coMat.HasValue ?
                new ObjectParameter("coMat", coMat) :
                new ObjectParameter("coMat", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemDSSV_HDRL", maSVParameter, maHDRLParameter, coMatParameter);
        }
    
        public virtual int spThemGiangVien(string magv, string tengv, string thuocmakhoa, string hocvi, string diachi, string sdt)
        {
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            var tengvParameter = tengv != null ?
                new ObjectParameter("tengv", tengv) :
                new ObjectParameter("tengv", typeof(string));
    
            var thuocmakhoaParameter = thuocmakhoa != null ?
                new ObjectParameter("thuocmakhoa", thuocmakhoa) :
                new ObjectParameter("thuocmakhoa", typeof(string));
    
            var hocviParameter = hocvi != null ?
                new ObjectParameter("hocvi", hocvi) :
                new ObjectParameter("hocvi", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemGiangVien", magvParameter, tengvParameter, thuocmakhoaParameter, hocviParameter, diachiParameter, sdtParameter);
        }
    
        public virtual int spThemHocPhan(string mahp, string mamh, Nullable<int> hocky, string namhoc, string magv, Nullable<int> sotc, Nullable<int> hocphi)
        {
            var mahpParameter = mahp != null ?
                new ObjectParameter("mahp", mahp) :
                new ObjectParameter("mahp", typeof(string));
    
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            var hockyParameter = hocky.HasValue ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(int));
    
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            var sotcParameter = sotc.HasValue ?
                new ObjectParameter("sotc", sotc) :
                new ObjectParameter("sotc", typeof(int));
    
            var hocphiParameter = hocphi.HasValue ?
                new ObjectParameter("hocphi", hocphi) :
                new ObjectParameter("hocphi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemHocPhan", mahpParameter, mamhParameter, hockyParameter, namhocParameter, magvParameter, sotcParameter, hocphiParameter);
        }
    
        public virtual int spThemKhoa(string maKhoa, string tenKhoa, string truongKhoa, string sDT)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("tenKhoa", tenKhoa) :
                new ObjectParameter("tenKhoa", typeof(string));
    
            var truongKhoaParameter = truongKhoa != null ?
                new ObjectParameter("truongKhoa", truongKhoa) :
                new ObjectParameter("truongKhoa", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemKhoa", maKhoaParameter, tenKhoaParameter, truongKhoaParameter, sDTParameter);
        }
    
        public virtual int spThemLop(string maLop, string chuyenNganh)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            var chuyenNganhParameter = chuyenNganh != null ?
                new ObjectParameter("chuyenNganh", chuyenNganh) :
                new ObjectParameter("chuyenNganh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemLop", maLopParameter, chuyenNganhParameter);
        }
    
        public virtual int spThemMonHoc(string maMH, string tenMH)
        {
            var maMHParameter = maMH != null ?
                new ObjectParameter("maMH", maMH) :
                new ObjectParameter("maMH", typeof(string));
    
            var tenMHParameter = tenMH != null ?
                new ObjectParameter("tenMH", tenMH) :
                new ObjectParameter("tenMH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemMonHoc", maMHParameter, tenMHParameter);
        }
    
        public virtual int spThemRL(string maHDRL, string tenHDRL, string diaDiem, Nullable<System.DateTime> ngayTC, string namHoc, Nullable<int> hocKy, Nullable<int> soDiemRL)
        {
            var maHDRLParameter = maHDRL != null ?
                new ObjectParameter("MaHDRL", maHDRL) :
                new ObjectParameter("MaHDRL", typeof(string));
    
            var tenHDRLParameter = tenHDRL != null ?
                new ObjectParameter("TenHDRL", tenHDRL) :
                new ObjectParameter("TenHDRL", typeof(string));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            var ngayTCParameter = ngayTC.HasValue ?
                new ObjectParameter("NgayTC", ngayTC) :
                new ObjectParameter("NgayTC", typeof(System.DateTime));
    
            var namHocParameter = namHoc != null ?
                new ObjectParameter("namHoc", namHoc) :
                new ObjectParameter("namHoc", typeof(string));
    
            var hocKyParameter = hocKy.HasValue ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(int));
    
            var soDiemRLParameter = soDiemRL.HasValue ?
                new ObjectParameter("SoDiemRL", soDiemRL) :
                new ObjectParameter("SoDiemRL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemRL", maHDRLParameter, tenHDRLParameter, diaDiemParameter, ngayTCParameter, namHocParameter, hocKyParameter, soDiemRLParameter);
        }
    
        public virtual int spThemSinhVien(string maSV, string hoTen, string diaChi, Nullable<System.DateTime> ngaySinh, string gioiTinh, string danToc, string queQuan, string maLop)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("danToc", danToc) :
                new ObjectParameter("danToc", typeof(string));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("queQuan", queQuan) :
                new ObjectParameter("queQuan", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemSinhVien", maSVParameter, hoTenParameter, diaChiParameter, ngaySinhParameter, gioiTinhParameter, danTocParameter, queQuanParameter, maLopParameter);
        }
    
        public virtual int spThemTaiKhoan(string maTk, string matKhau, string loaiUser, string ma)
        {
            var maTkParameter = maTk != null ?
                new ObjectParameter("maTk", maTk) :
                new ObjectParameter("maTk", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            var loaiUserParameter = loaiUser != null ?
                new ObjectParameter("loaiUser", loaiUser) :
                new ObjectParameter("loaiUser", typeof(string));
    
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemTaiKhoan", maTkParameter, matKhauParameter, loaiUserParameter, maParameter);
        }
    
        public virtual int spThemViPham(string maSV, string noiDung, string hinhthucKL, Nullable<System.DateTime> ngayVP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("noiDung", noiDung) :
                new ObjectParameter("noiDung", typeof(string));
    
            var hinhthucKLParameter = hinhthucKL != null ?
                new ObjectParameter("hinhthucKL", hinhthucKL) :
                new ObjectParameter("hinhthucKL", typeof(string));
    
            var ngayVPParameter = ngayVP.HasValue ?
                new ObjectParameter("ngayVP", ngayVP) :
                new ObjectParameter("ngayVP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemViPham", maSVParameter, noiDungParameter, hinhthucKLParameter, ngayVPParameter);
        }
    
        public virtual int spXoaChuyenNganh(string maCN)
        {
            var maCNParameter = maCN != null ?
                new ObjectParameter("maCN", maCN) :
                new ObjectParameter("maCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaChuyenNganh", maCNParameter);
        }
    
        public virtual int spXoaCTXH(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaCTXH", maHDParameter);
        }
    
        public virtual int spXoaDiemThi(string maSV, string maHP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maHPParameter = maHP != null ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaDiemThi", maSVParameter, maHPParameter);
        }
    
        public virtual int spXoaDSSV_HDCTXH(string maHD, string maSV)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(string));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaDSSV_HDCTXH", maHDParameter, maSVParameter);
        }
    
        public virtual int spXoaDSSV_HDRL(string maSV, string maHDRL)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maHDRLParameter = maHDRL != null ?
                new ObjectParameter("MaHDRL", maHDRL) :
                new ObjectParameter("MaHDRL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaDSSV_HDRL", maSVParameter, maHDRLParameter);
        }
    
        public virtual int spXoaGiangVien(string magv)
        {
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaGiangVien", magvParameter);
        }
    
        public virtual int spXoaHocPhan(string mahp)
        {
            var mahpParameter = mahp != null ?
                new ObjectParameter("mahp", mahp) :
                new ObjectParameter("mahp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaHocPhan", mahpParameter);
        }
    
        public virtual int spXoaKhoa(string maKhoa)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaKhoa", maKhoaParameter);
        }
    
        public virtual int spXoaLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaLop", maLopParameter);
        }
    
        public virtual int spXoaMonHoc(string maMH)
        {
            var maMHParameter = maMH != null ?
                new ObjectParameter("maMH", maMH) :
                new ObjectParameter("maMH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaMonHoc", maMHParameter);
        }
    
        public virtual int spXoaRL(string maHDRL)
        {
            var maHDRLParameter = maHDRL != null ?
                new ObjectParameter("MaHDRL", maHDRL) :
                new ObjectParameter("MaHDRL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaRL", maHDRLParameter);
        }
    
        public virtual int spXoaSinhVien(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaSinhVien", maSVParameter);
        }
    
        public virtual int spXoaTaiKhoan(string maTk)
        {
            var maTkParameter = maTk != null ?
                new ObjectParameter("maTk", maTk) :
                new ObjectParameter("maTk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaTaiKhoan", maTkParameter);
        }
    
        public virtual int spXoaViPham(string maSV, string noiDung, string hinhthucKL, Nullable<System.DateTime> ngayVP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("noiDung", noiDung) :
                new ObjectParameter("noiDung", typeof(string));
    
            var hinhthucKLParameter = hinhthucKL != null ?
                new ObjectParameter("hinhthucKL", hinhthucKL) :
                new ObjectParameter("hinhthucKL", typeof(string));
    
            var ngayVPParameter = ngayVP.HasValue ?
                new ObjectParameter("ngayVP", ngayVP) :
                new ObjectParameter("ngayVP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaViPham", maSVParameter, noiDungParameter, hinhthucKLParameter, ngayVPParameter);
        }
    }
}
