//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPHAM
    {
        public string MaSV { get; set; }
        public string NoiDung { get; set; }
        public string HinhThucKL { get; set; }
        public System.DateTime NgayViPham { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
